name: Continuous Integration

on: [push]

jobs:
  setup:
    runs-on: ubuntu-24.04-arm
    container:
      image: devxygmbh/r-alpine:4-3.21

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          apk update
          apk add harfbuzz-dev fribidi-dev
      - name: Set Repo
        run: |
          R -e 'options("repos")'
      - name: Install packages
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install("devtools")'
          R -q -e 'pak::pkg_install("data.table")'
      - name: Run scripts
        run: |
          R -q -e 'source("parse_data.R")'
