name: Continuous Integration

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-22.04-arm
    container: devxygmbh/r-alpine:4-3.21
    steps:
      - name: Manual Checkout
        run: |
          apk update
          apk add git
          git clone --depth 1 https://github.com/minnaheim/gha_demo.git
          git status

      - name: Current System Info
        run: |
          uname -a
      - name: Install system dependencies
        run: |
          apk add harfbuzz-dev fribidi-dev
      - name: Set Repo
        run: |
          R -e 'options("repos")'
      - name: Install packages
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install("data.table")'
          R -q -e 'pak::pkg_install("remotes")'
          R -q -e 'pak::pkg_install("gert")'
      - name: Run scripts
        run: |
          R -q -e 'source("parse_data.R")'
