name: Continuous Integration

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    container:
      image: devxygmbh/r-alpine:4-3.21
    steps:
      - name: Install packages
        run: |
          Rscript -e  'install.packages("data.table")'
      - name: Run scripts
        run: |
          Rscript R/parse_data.R

      # docker pull devxygmbh/r-alpine
      # docker run -it 6bebc005437b /bin/bash
      # R
      # install.packages()
