name: Continuous Integration

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    container:
      image: devxygmbh/r-alpine:4-3.21 # should be equivalent to: docker run -it  6bebc005437b
    steps:
      # - name: Session Info
      #   run: |
      #     'sessionInfo()'
      - name: Install packages
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install("gert")'
          R -q -e 'pak::pkg_install("devtools")'

      - name: Run scripts
        run: |
          R -q -e 'source("gha_demo/R/parse_data.R")'
