name: Continuous Integration

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    container:
      image: devxygmbh/r-alpine:4-3.21

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          apk update
          apk add harfbuzz-dev fribidi-dev
      - name: Install package - pak
        run: |
          R -q -e 'install.packages("pak", repos = "https://cran.devxy.io/arm64/alpine321/latest", type = "binary")'
      - name: pak install package - devtools
        run: |
          R -q -e 'pak::pkg_install("devtools")'
      - name: pak install package - data.table
        run: |
          R -q -e 'pak::pkg_install("data.table")'
      - name: Run scripts
        run: |
          R -q -e 'source("parse_data.R")'
