name: Continuous Integration

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          apk update
          apk add --no-cache harfbuzz-dev fribidi-dev freetype-dev libpng-dev glib-dev pkgconf

  build:
    runs-on: ubuntu-latest
    container:
      image: devxygmbh/r-alpine:4-3.21 # should be equivalent to: docker run -it  6bebc005437b
    steps:
      - name: Session Info
        run: |
          R -q -e 'sessionInfo()'
      - name: Install packages
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install("gert")'
          R -q -e 'pak::pkg_install("devtools")'

      - name: Run scripts
        run: |
          R -q -e 'source("gha_demo/R/parse_data.R")'
